
# Copyright (c) 2017-2024 King Abdullah University of Science and Technology,
# All rights reserved.
# ExaGeoStat is a software package, provided by King Abdullah University of Science and Technology (KAUST).

# @file Makefile
# @brief Makefile for custom building ExaGeoStat
# @version 1.1.0
# @author David Helmy
# @date 2024-01-30

# this file is added to let R CMD build with Custom build configuration instead of using its
# main build system
all :
